<script setup lang="ts">
// Locale-aware <head>: <html lang/dir>, canonical + hreflang alternates and
// og:locale for uz/ru/en — generated by @nuxtjs/i18n from the configured
// baseUrl so multilingual SEO is correct on every route.
const i18nHead = useLocaleHead({ dir: true, lang: true, seo: true })

useHead(() => ({
  htmlAttrs: i18nHead.value.htmlAttrs ?? {},
  link: i18nHead.value.link ?? [],
  meta: [
    ...(i18nHead.value.meta ?? []),
    { name: 'theme-color', content: '#2541e3' },
    { name: 'color-scheme', content: 'light' }
  ]
}))

// Site-wide social/SEO defaults; pages override title/description via
// useSeoMeta. Keeps OG/Twitter cards consistent across every route.
useSeoMeta({
  ogType: 'website',
  ogSiteName: 'rentmi.uz',
  twitterCard: 'summary_large_image'
})
</script>

<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
